// Generated by wrangler types; kept checked-in for local type checking without a Cloudflare login.

export interface Env {
  GITHUB_TOKEN: string;
  GITHUB_OWNER: string;
  GITHUB_REPO: string;
  API_CORS_ORIGIN?: string;
  DEVELOPER_API_GATEWAY: DurableObjectNamespace<import("./src/index").DeveloperApiGateway>;
}

declare module "cloudflare:workers" {
  interface Cloudflare.Env extends Env {}
}
