// Generated by wrangler types
interface Env {
  DEVELOPER_API_GATEWAY: DurableObjectNamespace<unknown>;
  GITHUB_TOKEN: string;
  GITHUB_OWNER?: string;
  GITHUB_REPO?: string;
  EMAIL?: SendEmail;
  CALLBACK_SECRET?: string;
}

declare module "cloudflare:workers" {
  interface Env {
    DEVELOPER_API_GATEWAY: DurableObjectNamespace<unknown>;
    GITHUB_TOKEN: string;
    GITHUB_OWNER?: string;
    GITHUB_REPO?: string;
    EMAIL?: SendEmail;
    CALLBACK_SECRET?: string;
  }
}